DEBUG:
  eval_in_train: 10
  eval_in_train_per_iter: -1
INPUT:
  CLASSES: ['background', 'wall', 'door', 'window', 'ceiling', 'floor'] 
  SCENES: ['0058113bdc8bee5f387bb5ad316d7b28', '00922f91aa09dbdda3a74489ea0e21eb']
MODEL:
  ROI__ONLY: True        
  SEPARATE_CLASSES: [['wall'], ['ceiling','floor']]
  LOSS:
    WEIGHTS: [2.0,2,1,1,  0, 0.01, 0.01] 
SOLVER:
  EPOCHS: 200
  EPOCHS_BETWEEN_TEST: 200
  IMS_PER_BATCH: 1
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.000
  LR_STEP_EPOCHS: (10,)
  CHECKPOINT_PERIOD_EPOCHS: 50
  WARMUP_EPOCHS: 4.0
  TRACK_RUNNING_STATS: False
OUTPUT_DIR: "RES/res_3g6c_Fpn4321_bs1_lr20"
TEST:
  IMS_PER_BATCH: 1
  IOU_THRESHOLD: 0.2
